name: CI

on: [push]

jobs:
  build:
    container: 
      image: docker://alpine
    steps:
      - with:
          entrypoint: tail -f /dev/null
        run: |
          echo hello
          apk add curl
          

      
