name: CI

on: [push]

jobs:
    build:
      runs-on: ubuntu-latest
      container:
        image: docker://alpine

      steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Validate and Upload Chart to Chart Museum
        run: |
          echo hello
          apk add curl

          
          

      
