name: CI

on: [push]

jobs:
  build:
    timeout_minutes: 4
    container: 
      image: docker://alpine
    steps:
      - run: |
          echo hello
          apk add curl
          
          

      
