name: CI

on: [push]

jobs:
  build:
    container: 
      image: alpine
    steps:
      - run: |
          echo hello
          apk add curl
        with:
          entrypoint: tail -f /dev/null
      
